title: Juan D. Raigoso E.
logo: CV_Juan-Raigoso/Foto/FotoFinal.png
description: Economista con más de 3 años de experiencia en análisis de datos e investigación económica y social.
show_downloads: true
theme: jekyll-theme-minimal
