title: Juan D. Raigoso E.
logo: CV_Juan-Raigoso/Foto/Foto.png
description: Economista con más de 3 años de experiencia en análisis de datos e investigación económica y social,
trabajando en el sector público y privado. Mi trayectoria incluye roles como coordinador del Observatorio Económico
y Social del municipio de Filandia y Economista en la Federación Nacional de Cultivadores de Cereales, Leguminosas
y Soya (Fenalce), donde implementé conocimientos estadísticos para el análisis y la toma de decisiones.
show_downloads: true
theme: jekyll-theme-minimal
